tasks:
  - init: yarn install && yarn run build
    command: yarn run dev

github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: true
    master: true
    branches: true
    pullRequestsFromForks: true

ports:
  - port: 3000
    onOpen: open-preview
