name: New Link 🔗
description: Use this to add new link into the Hub
title: "[Add] <write what you want to add>"
labels: ["chore", "goal: new-link"]
body:
  - type: input
    attributes:
      label: Site URL
      description: Provide complete/valid URL.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of the above provided site
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Category
      options:
        - Frontend
        - Backend
        - ML, AI & Data
        - Youtube
        - Resources
        - Languages
        - Open Source
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Sub Category
      description: For example "images", "fonts", "colors", "illustrations", "animations", "icons", "design inspiration", "testing", "themes & templates", "validation", "security", "authentication", "caching", "testings"
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I am willing to work on this issue (optional)"
          required: false
        
        - label: "I am a GSSoC'23 contributor"
          required: false
