name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: '[BUG] <write a small description here>'
labels: ['bug', 'goal: fix', 'priority: medium']
body:
  - type: textarea
    attributes:
      label: Description
      id: description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      id: screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional information?
      id: extrainfo
      description: Any additional information or Is there anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 'Checklist'
      options:
        - label: 'I have checked the existing issues'
          required: true

        - label: 'I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)'
          required: true

        - label: 'I am willing to work on this issue (optional)'
          required: false