name: Feature Request 💡
description: Have any new idea or new feature for LinksHub? Please suggest!
title: "[Feature] <description>"
labels: [" goal: addition"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of any alternative solution or features you've considered.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional Information
      description: Add any other context or anything else about this idea
    validations:
      required: false
