name: Other
description: Use this for any other question or issue. Please do not create blank issues
title: '[OTHER]'
labels: ['status: awaiting triage']
body:
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share or ask?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: 'Checklist'
      options:
        - label: 'I have checked the existing issues'
          required: true

        - label: 'I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)'
          required: true

        - label: 'I am willing to work on this issue (optional)'
          required: false
