name: Other 
description: Use this for any other question or issue. Please do not create blank issues
title: "[OTHER]"
labels: ["status: awaiting triage"]
body: 
  - type: textarea
    id: issuedescription
    attributes: 
      label: What would you like to share or ask? 
      description: Provide a clear and concise explanation of your issue.
    validations: 
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else you want to add ?  
    validations:
      required: false