// frontend
export { default as accessibility } from './frontend/accessibility.json'
export { default as animations } from './frontend/animations.json'
export { default as colors } from './frontend/colors.json'
export { default as designInspirations } from './frontend/design-inspirations.json'
export { default as fonts } from './frontend/fonts.json'
export { default as icons } from './frontend/icons.json'
export { default as illustrations } from './frontend/illustrations.json'
export { default as images } from './frontend/images.json'
export { default as onlineCodeEditors } from './frontend/online-code-editors.json'
export { default as themesTemplates } from './frontend/themes-templates.json'
export { default as uiGenerators } from './frontend/ui-generators.json'
export { default as react } from './frontend/react.json'
export { default as videos } from './frontend/videos.json'
// backend
export { default as authentication } from './backend/authentication.json'
export { default as architecture } from './backend/architecture.json'
export { default as caching } from './backend/caching.json'
export { default as security } from './backend/security.json'
export { default as testing } from './backend/testing.json'
export { default as validation } from './backend/validation.json'
export { default as systemDesign } from './backend/system-design.json'
export { default as database } from './backend/database.json'
export {default as api} from './backend/api.json'

//devops
export { default as cicd } from './DevOps/cicd.json'
export { default as devopsLifecycle } from './DevOps/devopsLifecycle.json'
export { default as devopsMethodologies } from './DevOps/devopsMethodologies.json'
export { default as docker } from './DevOps/docker.json'
export { default as kubernetes } from './DevOps/kubernetes.json'
export { default as microservices } from './DevOps/microservices.json'

// languages
export { default as javascript } from './languages/javascript.json'
export { default as python } from './languages/python.json'
export { default as golang } from './languages/golang.json'
export { default as csharp } from './languages/csharp.json'
export { default as typescript } from './languages/typescript.json'
export { default as ruby } from './languages/ruby.json'
export { default as CProgramming } from './languages/c-programming.json'
export { default as kotlin } from './languages/kotlin.json'
export { default as Rust } from './languages/rust.json'
export { default as java } from './languages/java.json'
export { default as cpp } from './languages/cpp.json'
export { default as dart } from './languages/dart.json'
//internet of things
export { default as coursera } from './internet_of_things/coursera.json'
export { default as raspberrypi } from './internet_of_things/raspberry.json'
//cloud computing
export { default as gcp } from './cloud_computing_platforms/gcp.json'
export { default as aws } from './cloud_computing_platforms/aws.json'
export { default as azure } from './cloud_computing_platforms/azure.json'
export { default as oracle } from './cloud_computing_platforms/oracle.json'
export { default as ibm } from './cloud_computing_platforms/ibm.json'
//artificial intelligence
export { default as artificialIntelligence } from './artificial_intelligence/artificial-intelligence.json'
export { default as ml } from './artificial_intelligence/machine-learning.json'
export { default as dataScience } from './artificial_intelligence/data-science.json'
export { default as deepLearning } from './artificial_intelligence/deep-learning.json'
// Open-source
export { default as openSourceBlogs } from './open_source/blogs.json'
export { default as openSourceProjects } from './open_source/projects.json'
export { default as openSourceTools } from './open_source/tools.json'
export { default as openSourceVideos } from './open_source/videos.json'
// resources
export { default as blogs } from './resources/blogs.json'
export { default as officialdocs } from './resources/official-docs.json'
export { default as hosting } from './resources/hosting.json'
export { default as ebook } from './resources/e-book.json'
export { default as project } from './resources/project-ideas.json'
export { default as events } from './other/events.json'
// youtube
export { default as android } from './youtube/android.json'
export { default as dataStructures } from './youtube/data-structures.json'
export { default as css } from './youtube/css.json'
export { default as machineLearning } from './youtube/machine-learning.json'
export { default as tensorflow } from './youtube/tensorflow.json'
export { default as webDevelopment } from './youtube/web-development.json'
export { default as web3metaverse } from './youtube/web3-metaverse.json'
export { default as youtubeTesting } from './youtube/testing.json'
export { default as computerScience } from './youtube/computer-science.json'
export { default as competitiveProgramming } from './youtube/competitive-programming.json'
export { default as fintech } from './youtube/fintech.json'
export { default as gameDevelopment } from './youtube/game-development.json'
// other
export { default as github } from './other/github.json'
export { default as devtools } from './other/devtools.json'
export { default as podcasts } from './other/podcasts.json'
export { default as otherResources } from './other/other-resources.json'
export { default as communities } from './other/communities.json'
