// frontend
export { default as accessibility } from './frontend/accessibility.json'
export { default as animations } from './frontend/animations.json'
export { default as colors } from './frontend/colors.json'
export { default as designInspirations } from './frontend/design-inspirations.json'
export { default as fonts } from './frontend/fonts.json'
export { default as icons } from './frontend/icons.json'
export { default as illustrations } from './frontend/illustrations.json'
export { default as images } from './frontend/images.json'
export { default as onlineCodeEditors } from './frontend/online-code-editors.json'
export { default as themesTemplates } from './frontend/themes-templates.json'
export { default as uiGenerators } from './frontend/ui-generators.json'
export { default as react } from './frontend/react.json'
export { default as next } from './frontend/next.json'
export { default as three } from './frontend/three.json'
export { default as uilibraries } from './frontend/ui-libraries.json'
// backend
export { default as authentication } from './backend/authentication.json'
export { default as architecture } from './backend/architecture.json'
export { default as caching } from './backend/caching.json'
export { default as security } from './backend/security.json'
export { default as testing } from './backend/testing.json'
export { default as validation } from './backend/validation.json'
export { default as systemDesign } from './backend/system-design.json'
export { default as database } from './backend/database.json'
export { default as api } from './backend/api.json'
export { default as emailProviders } from './backend/email-providers.json'

//devops
export { default as cicd } from './devops/cicd.json'
export { default as devopsLifecycle } from './devops/devops-life-cycle.json'
export { default as devopsMethodologies } from './devops/devops-methodologies.json'
export { default as docker } from './devops/docker.json'
export { default as jenkins } from './devops/jenkins.json'
export { default as kubernetes } from './devops/kubernetes.json'
export { default as microservices } from './devops/microservices.json'
export { default as iac } from './devops/iac.json'

// languages
export { default as javascript } from './languages/javascript.json'
export { default as python } from './languages/python.json'
export { default as golang } from './languages/golang.json'
export { default as csharp } from './languages/csharp.json'
export { default as typescript } from './languages/typescript.json'
export { default as ruby } from './languages/ruby.json'
export { default as CProgramming } from './languages/c-programming.json'
export { default as kotlin } from './languages/kotlin.json'
export { default as Rust } from './languages/rust.json'
export { default as java } from './languages/java.json'
export { default as cpp } from './languages/cpp.json'
export { default as dart } from './languages/dart.json'
export { default as solidity } from './languages/solidity.json'
export { default as swift } from './languages/swift.json'
//internet of things
export { default as coursera } from './internet_of_things/coursera.json'
export { default as raspberrypi } from './internet_of_things/raspberrypi.json'
//cloud computing
export { default as gcp } from './cloud_computing_platforms/gcp.json'
export { default as aws } from './cloud_computing_platforms/aws.json'
export { default as azure } from './cloud_computing_platforms/azure.json'
export { default as oracle } from './cloud_computing_platforms/oracle.json'
export { default as ibm } from './cloud_computing_platforms/ibm.json'
//cyber_security
export { default as offensive_security } from './cybersecurity/offensive_security.json'
export { default as defensive_security } from './cybersecurity/defensive_security.json'
export { default as malware_analysis } from './cybersecurity/malware_analysis.json'
export { default as web_security } from './cybersecurity/web_application_security.json'
//artificial intelligence
export { default as artificialIntelligence } from './artificial_intelligence/artificial-intelligence.json'
export { default as ml } from './artificial_intelligence/machine-learning.json'
export { default as dataScience } from './artificial_intelligence/data-science.json'
export { default as deepLearning } from './artificial_intelligence/deep-learning.json'
export { default as nlp } from './artificial_intelligence/NLP.json'
// Open-source
export { default as openSourceArticles } from './open_source/articles.json'
export { default as openSourcePrograms } from './open_source/os-programs.json'
export { default as openSourceProjects } from './open_source/projects.json'
export { default as openSourceTools } from './open_source/tools.json'
export { default as openSourceTutorials } from './open_source/tutorials.json'
// resources
export { default as blogs } from './resources/blogs.json'
export { default as officialdocs } from './resources/official-docs.json'
export { default as hosting } from './resources/hosting.json'
export { default as ebook } from './resources/e-book.json'
export { default as project } from './resources/project-ideas.json'
export { default as dsa } from './resources/dsa.json'
export { default as events } from './other/events.json'
// youtube
export { default as android } from './youtube/android.json'
export { default as css } from './youtube/css.json'
export { default as machineLearning } from './youtube/machine-learning.json'
export { default as Kubernetes } from './youtube/Kubernetes.json'
export { default as tensorflow } from './youtube/tensorflow.json'
export { default as webDevelopment } from './youtube/web-development.json'
export { default as web3metaverse } from './youtube/web3-metaverse.json'
export { default as softwareTesting } from './youtube/software-testing.json'
export { default as computerScience } from './youtube/computer-science.json'
export { default as fintech } from './youtube/fintech.json'
export { default as gameDevelopment } from './youtube/game-development.json'
// other
export { default as github } from './other/github.json'
export { default as git } from './other/git.json'
export { default as devtools } from './other/devtools.json'
export { default as podcasts } from './other/podcasts.json'
export { default as otherResources } from './other/other-resources.json'
export { default as communities } from './other/communities.json'
export { default as roadmaps } from './other/roadmaps.json'
export { default as domains } from './other/domains.json'
export { default as textFormatting } from './other/text-formatting.json'
// competitive programming
export { default as cpPlatforms } from './competitive_programming/cp-platforms.json'
export { default as cpTutorials } from './competitive_programming/cp-tutorials.json'
// technical-writing
export { default as technicalWritingTools } from './technical-writing/tools.json'
// Placement-Preparation
export { default as interviewPreparation } from './placement_prep/interview-preparation.json'
export { default as jobPortals } from './placement_prep/job-portals.json'
export { default as resumeBuilding } from './placement_prep/resume-building.json'
export { default as portfolioBuilding } from './placement_prep/portfolio-building.json'
export { default as coverLetters } from './placement_prep/cover-letters.json'
export { default as certifications } from './placement_prep/certifications.json'
//DSA
export { default as dsaArticles } from './data_structures/dsa-articles.json'
export { default as dsaTutorials } from './data_structures/dsa-tutorials.json'
export { default as dsaCourses } from './data_structures/dsa-courses.json'
// Block Chain
export { default as smartContracts } from './BlockChain/smart-contracts.json'
export { default as truffle } from './BlockChain/truffle.json'
export { default as hardhat } from './BlockChain/hardhat.json'
export { default as ethers } from './BlockChain/ethers.json'
