import React from "react";
import Head from "next/head";
import { SideNavbar } from "../components/SideNavbar";
import { MainContainer } from "../components/MainContainer";
import { LinksContainer } from "../components/LinksConatiners";

export default function Home() {
  return (
    <>
      <Head>
        <title>LinksHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" className="rounded-full" />
      </Head>
      <div className="lg:flex flex-wrap justify-between">
        <SideNavbar />
        <main className="">
          {/* <MainContainer /> */}
          <LinksContainer />
        </main>
      </div>
    </>
  );
}
